### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by ogabek96** [apertium/apertium-tur-uzb#1]
When I type ./autogen.sh
I am getting this error:

configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
Makefile.am: installing './INSTALL'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for gawk... (cached) gawk
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for APERTIUM... yes
checking for hfst-lexc... /usr/bin/hfst-lexc
checking for hfst-twolc... /usr/bin/hfst-twolc
checking for cg-comp... /usr/bin/cg-comp
checking for cg-proc... /usr/bin/cg-proc
checking for lrx-comp... /usr/bin/lrx-comp
checking for lrx-proc... /usr/bin/lrx-proc
checking for gzcat... no
checking for zcat... /bin/zcat
checking for APERTIUM_TUR... no
configure: error: Package requirements (apertium-tur) were not met:

No package 'apertium-tur' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables APERTIUM_TUR_CFLAGS
and APERTIUM_TUR_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by ftyers** [comment]
You need to use `--with-lang1=/path/to/apertium-tur --with-lang2=/path/to/apertium-uzb`.

**Comment by ogabek96** [comment]
Thank you I forgot
